### PR TITLE
Adds bootstrap icons dependency and includes font/bootstrap-icons.css

### PR DESCRIPTION
**Pull request by MarkovianPD**

### CODE REVIEW

**Comment by fabiopacifici** [comment]
Hi mate thanks for your effort but the PR cannot be merged or reviewed as there are too many changes introduced in your branch. 

I see you pushed the node_module folder, this should never be pushed to github as rule of thumb.

Please note that this is a package and not a standard laravel application and therefore the package.json is not the in the root folder of the repo.  

To add the bootstrap-icons dependency to the package we add the dependecy as it appears in the package.json to the laravel_9_package package.json file that is inside /src/stubs/ folder.

Then you need to include in the app.scss file the path to the bootstrap-icons css file.
 
The same is done in the stubs/auth folder that also includes a package.json file. Feel free to ask if you have any doubt

**Comment by MarkovianPD** [comment]
> 

Thank you very much for your explanation and patience! I will adjust and fix according to your comments! Second times a charm!

**Comment by MarkovianPD** [comment]
@fabiopacifici I believe I have made the adjustments correctly!

**Comment by MarkovianPD** [comment]
Hello just checking if this was the correct solution?

**Pull request closed without merging**
