### PR TITLE
fixed for laravel 10.2 compability

### PR DESCRIPTION
**Pull request by MatteoLucerni**

### CODE REVIEW

**Comment by MatteoLucerni** [comment]
Ciao, ho sistemato la compatibilità laravel 10.2 con delle piccole modifiche.
Ho rimosso la riga type:module dal package.json di Laravel che causava problemi
E sistemato un ; mancante in app.scss di auth

Spero ti possa interessare :D

**Comment by fabiopacifici** [comment]
Hi, thanks for your PR.

The package was already tested on laravel 10 when released and shown no issues.

Can you explain what issue you are trying to solve with this pr? 

Have you got an error message of some kind when installing the package? 

Your solution seems to look for a piece of text in the package json and remove it. 

However, since this package is not directly adding the string you are trying to delete, I would not introduce a fix that might affect other packages without first knowing the cause.

Thanks for your help 😊

**Comment by MatteoLucerni** [comment]
Hi Fabio. Thanks for your kind reply!

I know it's something that shouldn't be done because this can affect other packets but after laravel version 10.22 the package gives an error when you try to execute "npm run dev". 
The problem is solved if you delete in the file package.json the line with "type": "module" so that's what my solution is trying to do.

Also i did a small fix on a missing semicolon in the app.css of auth.

Thanks for your time, and i hope in another your reply!

Matteo

Screenshot of the error:
image

**Comment by fabiopacifici** [comment]
Closing this issue, as two a working solution have been proposed on the package documentation

**Pull request closed without merging**
